version: 2.1

workflows:
  main:
    jobs:
      - check
      - test_36
      - test_37
      - test_38


jobs:
  test_36: &test_template
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: py36

    steps:
      - checkout
      - run:
          name: run tests
          command: tox
  test_37:
    <<: *test_template
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV: py37

  test_38:
    <<: *test_template
    docker:
      - image: circleci/python:3.8
    environment:
      TOXENV: py37

  check:
    docker:
      - image: circleci/python:3.8
    environment:
      TOXENV: flake8
    steps:
      - checkout
      - run:
          name: Install black
          command: pip install flake8
      - run:
          command: black --check

