version: 2.1

workflows:
  main:
    jobs:
      - test
      - check


jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./manage.py test
          name: Test
  check:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: "Install black"
          command: "black --check"

