version: 2.1

workflows:
  main:
    jobs:
      - check
      - test_36
      - test_37
      - test_38


jobs:
  test_36: &test_template
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: py36

    steps:
      - checkout
      - run:
          name: Install tox
          command: pip install tox
      - run:
          name: Run tests
          command: |
            echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
            mkdir /tmp/test_reports
            tox -- --junitxml=/tmp/test_reports/junit.xml
      - store_test_results:
          path: /tmp/test_reports
  test_37:
    <<: *test_template
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV: py37

  test_38:
    <<: *test_template
    docker:
      - image: circleci/python:3.8
    environment:
      TOXENV: py38

  test_38_unit:
    <<: *test_template
    docker:
      - image: circleci/python:3.8
    environment:
      TOXENV: py38unit


  check:
    <<: *test_template
    environment:
      TOXENV: flake8
    steps:
      - checkout
      - run:
            name: Install tox
            command: pip install tox
      - run:
          name: Check code style
          command: tox

